https

diff --git a/https_ssl/0-world_wide_web b/https_ssl/0-world_wide_web
--- a/https_ssl/0-world_wide_web
+++ b/https_ssl/0-world_wide_web
@@ -1,21 +1,28 @@
-#!/usr/bin/env bash
-# This script audits DNS records for specified subdomains of a domain.
+#!/bin/bash
 
-function audit_subdomain {
-    local domain="$1"
-    local subdomain="$2"
-
-    if [ -z "$subdomain" ]; then
-        subdomains=("www" "lb-01" "web-01" "web-02")
-    else
-        subdomains=("$subdomain")
-    fi
-
-    for sub in "${subdomains[@]}"; do
-        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
-        destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
-        echo "The subdomain $sub is a $record_type record and points to $destination"
-    done
+# Function to query DNS records for a subdomain
+query_dns() {
+    local domain=$1
+    local subdomain=$2
+    
+    # Lookup DNS records using dig and awk for parsing
+    dig +short $subdomain.$domain | awk -v sub=$subdomain '{print "The subdomain " sub " is a " $1 " record and points to " $NF }'
 }
 
-audit_subdomain "$1" "$2"
+if [ $# -eq 0 ]; then
+    echo "Domain and subdomain parameters are required."
+    exit 1
+fi
+
+domain=$1
+subdomain=${2:-www}
+
+case $subdomain in
+    www|lb-01|web-01|web-02)
+        query_dns $domain $subdomain
+        ;;
+    *)
+        echo "Invalid subdomain."
+        exit 1
+        ;;
+esac
